### PR TITLE
Simply Django version in tox

### PR DESCRIPTION
**Pull request by ad-m**

### CODE REVIEW

**Comment by francbartoli** [comment]
@ad-m travis doesn't pass. Can you have a look?

**Comment by ad-m** [comment]
In ```TOX_ENV=py34-django-18``` fail with message:
> Collecting version (from experiment===0.0.2.dev-16d417d->-r requirements_test.txt (line 9))
>   Downloading https://files.pythonhosted.org/packages/fd/b6/fa3b2c859d4d8817a106e4272029d78a2afbca0a27139997a4e5515bbf60/version-0.1.1.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-gd7xdrhr/version/setup.py", line 4, in <module>
>         from version import __version__
>       File "/tmp/pip-install-gd7xdrhr/version/version.py", line 2, in <module>
>         from itertools import izip_longest
>     ImportError: cannot import name 'izip_longest'
due:
> izip_longest was renamed to zip_longest in Python 3 (note, no i at the start)

In ```requirements_test.txt``` we have:
> git+git://github.com/francbartoli/experiment@devel
which require ```version``` which is not compatibile with Python in version ```0.1.1```. See https://github.com/keleshev/version/blob/0.1.1/version.py#L2 , https://github.com/keleshev/version/blob/master/version.py . 

This means that the defect is a general problem of this project and is outside the scope of this PR.

**Comment by francbartoli** [comment]
That's true @ad-m, thanks for remembering me the actual problem

**Comment by francbartoli** [comment]
Btw, the fix was merged https://github.com/keleshev/version/pull/8 but nobody pushed to pypi yet :(

**Pull request merged**
